alias g="git"
alias ga="git add"
alias gc="git commit -v"
alias gd="git diff"
alias gl="git pull"
alias glg="git log --stat"
alias gp="git push"
alias gst="git status"

alias l="lsd -l"
alias cp="cp -iv"
alias diff="diff --color=auto"
alias grep="grep --color=auto"
alias ls="ls --color"
alias mkd="mkdir -pv"
alias mv="mv -iv"
alias rm="rm -vI"
alias rsync="rsync -vrPlu"

alias upgrade-gentoo="emerge --ask --verbose --update --deep --newuse @world"
